name: Destroy Stratosphere Container Web App
on:
  repository_dispatch:
    types: delete_stratosphere_container_web
jobs:
  delete-container-web-app:      
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      AZURE_CONTAINER_WEB_APP_NAME: "${{ github.event.client_payload.webapp_name }}"
      STRATOSPHERE_API_URL: https://api.live.external.byp.ai
      PROJECT_NAME: "${{ github.event.client_payload.project_name }}"
      GEOGRAPHY: "${{ github.event.client_payload.geography }}"
      STRATOSPHERE_ACCESS_TOKEN: "${{ github.event.client_payload.stratospher_access_token }}"
    steps:  
    - name: Checkout Code
      uses: actions/checkout@v2
        
    - name: Destroy Stratosphere Container Web
      run: |
        curl -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ env.STRATOSPHERE_ACCESS_TOKEN }}" \
          --request GET \
          ${{ env.STRATOSPHERE_API_URL }}/geographies/${{ env.GEOGRAPHY }}/projects/${{ env.PROJECT_NAME }}/resources/container-web/${{ env.AZURE_CONTAINER_WEB_APP_NAME }} > temp.json
          CONTAINER_WEB_APP_NAME=`cat temp.json | jq -r '.name'`
          echo $CONTAINER_WEB_APP_NAME
          if [[ -z "$CONTAINER_WEB_APP_NAME" ]]; then
            echo "null"
          else
            echo "$AZURE_CONTAINER_WEB_APP_NAME not found"
            exit 1
          fi