name: Destroy Stratosphere Container Web App
on:
  repository_dispatch:
    types: delete_stratosphere_container_web
jobs:
  delete-container-web-app:      
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      AZURE_CONTAINER_WEB_APP_NAME: "${{ github.event.client_payload.webapp_name }}"
      STRATOSPHERE_API_URL: https://api.live.external.byp.ai
      PROJECT_NAME: "${{ github.event.client_payload.project_name }}"
      GEOGRAPHY: "${{ github.event.client_payload.geography }}"
      STRATOSPHERE_ACCESS_TOKEN: "${{ github.event.client_payload.stratospher_access_token }}"
    steps:  
    - name: Checkout Code
      uses: actions/checkout@v2
        
    - name: Destroy Stratosphere Container Web
      run: |
        curl -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ env.STRATOSPHERE_ACCESS_TOKEN }}" \
          --request PUT \
          --data '{"spec": {"container_registry": {"access_policies": [{"name": "spn-alm", "type": "resource"},{"name": "grp-sec-saas-sub-lplat-test-reader", "type": "group"}]}}}' \
          ${{ env.STRATOSPHERE_API_URL }}/geographies/${{ env.GEOGRAPHY }}/projects/${{ env.PROJECT_NAME }}/resources/azure-container-registry/${{ env.AZURE_ACR_NAME }} > temp.json
          echo "AZURE_ACR_REPO_NAME=$(jq -r '.status.azure.resource_name' temp.json)" >> $GITHUB_ENV
          AZURE_ACR_STATUS=`cat temp.json | jq -r '.resources.name'`
          echo $AZURE_ACR_STATUS